name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  afficher-infos-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher le numéro et l’auteur de la PR
        run: |
          echo "Numéro de PR : ${{ github.event.pull_request.number }}"
          echo "Auteur de la PR : ${{ github.event.pull_request.user.login }}"