name: Scheduled Workflow

on:
  schedule:
    - cron: "0 9 * * 1-5"

jobs:
  tache-planifiee:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher la date d exécution
        run: date

      - name: Afficher l’environnement sélectionné
        run: |
          echo "Environnement sélectionné : ${{ inputs.environment || 'dev' }}"